### PR TITLE
:sparkles: Add csv with urls as input

### PR DESCRIPTION
**Pull request by karlangadas**
this commit fixes issue #4

### CODE REVIEW

**Comment by sagnik20** [comment]
Hey! Thank You for your efforts. Please discuss the issues before making a pull request or starting to work on it. :) 

The wanted case was input either from csv or text file. See, if you can do that.

**Comment by karlangadas** [comment]
Ohhh, ok! Is it ok if theres an input with the name of the file?

**Comment by sagnik20** [comment]
This works fine when some txt file is given as input. But when some csv file is given as input it gives the following error on line 13:

```
Enter the file name with websites url: a.csv
Traceback (most recent call last):
  File "C:/Users/A/Email-Scraper/email.py", line 13, in <module>
    original_url = pd.read_csv(url_file_name, header=header, names=['url'])['url'].tolist()
  File "C:\Users\A\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\A\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\A\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\A\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\A\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 1906, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 762, in pandas._libs.parsers.TextReader._get_header
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

Process finished with exit code 1
```

See if you can fix it.

**Comment by karlangadas** [comment]
Do you know if the file has any special encoding different form UTF-8?

**Comment by sagnik20** [comment]
> Do you know if the file has any special encoding different form UTF-8?

@karlangadas I don't think so. I simply created a normal csv file with a link in it.

**Comment by sagnik20** [comment]
Alright I'm accepting this PR as it works well with txt file. But I would expect you to open a new Issue and a PR solving the csv problem. :)

**Pull request merged**
